---
- name: Create or remove iSCSI target {{ target.name }}
  targetcli_iscsi:
    wwn: "{{ target.name }}"
    state: "{{ target.state | default('present') }}"
  notify:
    - save targetcli configuration

- name: Create or remove backstore objects for target {{ target.name }}
  targetcli_backstore:
    backstore_type: "{{ disk.type | default(iscsi_default_disk_type) }}"
    backstore_name: "{{ disk.name }}"
    options: " {{ disk.path }} "
    state: "{{ target.state | default('present') }}"
  with_items:
    - "{{ target.disks }}"
  loop_control:
    loop_var: "disk"
  notify:
    - save targetcli configuration

- name: Define ACLs for iSCSI target {{ target.name }}
  targetcli_iscsi_acl:
    wwn: "{{ target.name }}"
    initiator_wwn: "{{ initiator.name }}"
  with_items:
    - "{{ target.initiators | default(iscsi_default_initiators) }}"
  when: target.state|default("present") == "present"
  loop_control:
    loop_var: "initiator"
  notify:
    - save targetcli configuration
  no_log: true

- name: Configure authentication for target {{ target.name }}
  targetcli_iscsi_auth:
    wwn: "{{ target.name }}"
    initiator_wwn: "{{ initiator.name }}"
    userid: "{{ initiator.authentication.userid }}"
    password: "{{ initiator.authentication.password }}"
    userid_mutual: "{{ initiator.authentication.userid_mutual | default(omit) }}"
    password_mutual: "{{ initiator.authentication.password_mutual | default(omit) }}"
  notify:
    - save targetcli configuration
  when: target.state|default("present") == "present"
  loop_control:
    loop_var: "initiator"
  with_items:
    - "{{ target.initiators | default(iscsi_default_initiators) }}"
  no_log: true

- name: Remove default portal for {{ target.name }}
  targetcli_iscsi_portal:
    wwn: "{{ target.name }}"
    ip: "0.0.0.0"
    state: absent
  notify:
    - save targetcli configuration
  when: target.state|default("present") == "present"

- name: Create portal for target {{ target.name }}
  targetcli_iscsi_portal:
    wwn: "{{ target.name }}"
    ip: "{{ portal.ip }}"
    port: "{{ portal.port | default(omit) }}"
  notify:
    - save targetcli configuration
  when: target.state|default("present") == "present"
  loop_control:
    loop_var: "portal"
  with_items:
    - "{{ target.portals | default(iscsi_default_portals) }}"

- name: Assign backstores to initiators for target {{ target.name }}
  targetcli_iscsi_lun:
    wwn: "{{ target.name }}"
    backstore_type: "{{ disk.type | default(iscsi_default_disk_type) }}"
    backstore_name: "{{ disk.name }}"
  with_items:
    - "{{ target.disks }}"
  when: target.state|default("present") == "present"
  loop_control:
    loop_var: "disk"
  notify:
    - save targetcli configuration
