---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:

    storage_partitions:
      - name: /dev/vdb
        number: 1
        part_end: 100MB
      - name: /dev/vdb
        number: 2
        flags:
          - lvm
        part_start: 100MB
        part_end: 300MB
      - name: /dev/vdb
        number: 3
        flags:
          - lvm
        part_start: 300MB
        part_end: 100%
    storage_volumegroups:
      - name: vg_local
        devices:
          - /dev/vdb2
      - name: vg_iscsi
        devices:
          - /dev/vdb3
    storage_volumes:
      - name: vg_iscsi_lv_node1
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node2
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node3
        vg: vg_iscsi
        size: 100
      - name: vg_iscsi_lv_node4
        vg: vg_iscsi
        size: 100
      - name: vg_local_lv_data
        vg: vg_local
        size: 100

    iscsi_targets: []
      - name: "iqn.2021-07.com.ricsanfre:{{ ansible_host }}"
        disks:
          - name: vm3
            path: testing/vm2
            type: iblock    
  roles:
    - ricsanfre.storage
    - ricsanfre.iscsitarget
